[build]
  command = "npm run production"
  functions = "./functions"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"