backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
local_backend: true
# publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
# media_library:
#   name: cloudinary
#   config:
#     cloud_name: peterbroom
#     api_key: 378533634851541
collections:
  - label: "Sitewide Options"
    name: options
    files:
      - label: "Globals"
        name: headerGlobals
        file: "_data/headerGlobals.yml"
        fields:
          - label: "Site title"
            name: "siteTitle"
            field: {label: Name, name: name, widget: string}
          - label: "Tagline"
            name: "tagline"
            field: {label: Name, name: name, widget: string}
      - label: "Meta data"
        name: headerMeta
        file: "_data/headerMeta.yml"
        fields:
          - label: "Meta description"
            name: "description"
            # hint: "Use a generic description to describe the objective of this website",
            field: {label: Name, name: name, widget: text}
          - label: "Meta keywords"
            name: "keywords"
            widget: list
            add_to_top: true
            minimize_collapsed: true
            required: true
            summary: '{{fields.name}}'
            # hint: "Use generic terms for keywords searches. These keywords will also appear across all pages.",
            field: {label: Name, name: name, widget: string}

      - label: "Navigation Menu"
        name: headerNav
        file: "_data/headerNav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - { label: "Display Text", name: displayText, widget: string }
              - { label: URL, name: url, widget: string }

      - label: "Footer Menu"
        name: footerNav
        file: "_data/footerNav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - { label: "Display Text", name: displayText, widget: string }
              - { label: URL, name: url, widget: string }
      # - label: "Categories"
      #   name: categories
      #   file: "_data/categories.yml"
      #   fields:
      #     - label: "Category"
      #       label_singular: "Category"
      #       name: categoryitems
      #       widget: list
      #       fields:
      #         - { label: "Category", name: categoryText, widget: string }
      #         - { label: Category Slug, name: categorySlug, widget: string }
      # - label: "Submenus"
      #   name: subMenu
      #   file: "_data/subMenu.yml"
      #   fields:
      #     - label: "Nav Items"
      #       label_singular: "Nav Item"
      #       name: navItems
      #       widget: list
      #       summary: "{{fields.navtitle}}"
      #       collapsed: true
      #       types:
      #         - label: "Navigation List"
      #           name: navList
      #           widget: list
      #           fields:
      #             - label: "Navigation Title"
      #               name: "navtitle"
      #               widget: string
      #             - {
      #                 label: "Parent page",
      #                 widget: relation,
      #                 name: parent_relation,
      #                 required: true,
      #                 multiple: false,
      #                 collection: pages,
      #                 valueField: "{{slug}}",
      #                 searchFields: ["title"],
      #                 displayFields: ["title"],
      #               }
      #             - label: "Navigation item"
      #               name: navItem
      #               widget: object
      #               fields:
      #                 - label: "Add a Link"
      #                   name: link
      #                   widget: list
      #                   summary: "{{fields.displayText}}"
      #                   collapsed: true
      #                   types:
      #                     - label: "Link"
      #                       name: linkObject
      #                       widget: object
      #                       fields:
      #                         - {
      #                             label: "Display Text",
      #                             name: displayText,
      #                             widget: string,
      #                             required: true,
      #                           }
      #                         - {
      #                             label: "page",
      #                             widget: relation,
      #                             name: url,
      #                             required: true,
      #                             multiple: false,
      #                             collection: pages,
      #                             valueField: "{{slug}}",
      #                             searchFields: ["title"],
      #                             displayFields: ["title"],
      #                           }
  # - name: sections
  #   label: Sections
  #   label_singular: "Section"
  #   title: Sections
  #   folder: src/content/sections
  #   create: true
  #   identifier_field: name
  #   summary: '{{fields.sectionName}}'
  #   editor:
  #     preview: false
  #   fields:
  #     - {
  #         label: "Name",
  #         name: "sectionName",
  #         widget: "string",
  #         required: true,
  #       }
  #     - {
  #         label: "Slug",
  #         name: "sectionSlug",
  #         widget: "string",
  #         default: {{fields.sectionName}},
  #         required: true,
  #       }

  - name: pages
    label: Pages
    label_singular: "Page"
    title: Page
    folder: site/pages
    create: true
    nested:
      depth: 6 # max depth to show in the collection tree
      summary: "{{meta.path}}"
    slug: "{{slug}}"
    identifier_field: name
    editor:
      preview: false
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "site/includes/layouts/page.njk",
        }
      - {
          label: "Permalink",
          name: "permalink",
          widget: "string",
          required: true,
          default: "main/sub/index.html",
          hint: "Must be relative path (e.g. main/sub/index.html). Don't forget the .html extension",
        }
      - {
          label: "Parent key",
          name: parentKey,
          widget: relation,
          required: true,
          multiple: false,
          collection: pages,
          valueField: "{{slug}}",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Content Blocks"
        label_singular: "Content Block"
        name: blocks
        widget: list
        types:
          - label: "Hero"
            name: hero
            widget: object
            fields:
              - { label: "Heading", name: heading, widget: string }
              - {
                  label: "Content",
                  name: content,
                  widget: markdown,
                  buttons: ["bold", "italic", "link"],
                  required: false,
                }
          - label: "Body copy"
            name: textBlock
            widget: object
            fields:
              - {
                  label: "Heading",
                  name: heading,
                  widget: string,
                  required: false,
                }
              - { label: "Content", name: content, widget: markdown }
      - {
          label: "Related content",
          name: url,
          title: title,
          hint: "Link to other pages that relate to this content.",
          widget: relation,
          required: false,
          multiple: true,
          collection: pages,
          valueField: "{{slug}}",
          searchFields: ["title"],
          displayFields: ["title"],
        }
      - label: "Exclude from navigation"
        name: eleventyExcludeFromCollections
        required: false
        widget: "boolean"
        default: false
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - {
          label: "Meta description",
          name: "metaDescription",
          widget: "text",
          required: true
        }
      - {
          label: "Meta keywords",
          name: "metaKeywords",
          widget: list,
          add_to_top: true,
          minimize_collapsed: true,
          required: true,
          summary: '{{fields.name}}',
          field: {label: Name, name: name, widget: string}
        }
    meta:
      {
        path:
          {
            widget: string,
            label: "Path",
            index_file: "index",
            hint: "Path can be a sub-folder (e.g. main/sub)",
          },
      }
