backend:
  # repo: https://github.com/PeterBroom/portfolio.git
  name: git-gateway
  branch: main
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
local_backend: true
# publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: peterbroom
    api_key: 378533634851541

collections:
  - label: "Sitewide Options"
    name: options
    files:
      - label: "Globals"
        name: headerGlobals
        file: "_data/headerGlobals.yml"
        fields:
          - label: "Site title"
            name: "siteTitle"
            field: {label: Name, name: name, widget: string}
          - label: "Tagline"
            name: "tagline"
            field: {label: Name, name: name, widget: string}
      - label: "Meta data"
        name: headerMeta
        file: "_data/headerMeta.yml"
        fields:
          - label: "Meta description"
            name: "description"
            # hint: "Use a generic description to describe the objective of this website",
            field: {label: Name, name: name, widget: text}
          - label: "Meta keywords"
            name: "keywords"
            widget: list
            add_to_top: true
            minimize_collapsed: true
            required: true
            summary: '{{fields.name}}'
            # hint: "Use generic terms for keywords searches. These keywords will also appear across all pages.",
            field: {label: Name, name: name, widget: string}

      - label: "Navigation Menu"
        name: headerNav
        file: "_data/headerNav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - { label: "Display Text", name: displayText, widget: string }
              - { label: URL, name: url, widget: string }

      - label: "Footer Menu"
        name: footerNav
        file: "_data/footerNav.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: topLevelItems
            widget: list
            fields:
              - { label: "Display Text", name: displayText, widget: string }
              - { label: URL, name: url, widget: string }

  - name: "blog"
    label: "Blogs"
    label_singular: "Blog"
    title: Blog
    folder: "site/blog"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    editor:
      preview: false
    fields:
      - {
          label: "Layout", name: "layout", widget: "select",
          options:
            - { label: "Blog index page", value: "blog" }
            - { label: "Post", value: "post" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Sub heading", name: "sub_heading", widget: "string", required: false }
      - { label: "Image", name: post_image, widget: image,
          media_library: {
            name: cloudinary,
            output_filename_only: true
          }
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["blog", "post"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    title: Page
    folder: "site/pages"
    create: true
    nested:
      depth: 6 # max depth to show in the collection tree
      summary: "{{meta.path}}"
    slug: "{{slug}}"
    identifier_field: name
    editor:
      preview: false
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "page",
        }
      - {
          label: "Permalink",
          name: "permalink",
          widget: "string",
          required: true,
          hint: "Must be relative path (e.g. main/sub/index.html). Don't forget the .html extension",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Sub heading", name: "sub_heading", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Content Blocks"
        label_singular: "Content Block"
        name: blocks
        widget: list
        types:
          - label: "Hero"
            name: hero
            widget: object
            fields:
              - { label: "Heading", name: heading, widget: string }
              - { label: "Image", name: image, widget: image,
                  media_library: {
                    name: cloudinary,
                    output_filename_only: true
                  }
                }
              - {
                  label: "Content",
                  name: content,
                  widget: markdown,
                  buttons: ["bold", "italic", "link"],
                  required: false,
                }
          - label: "Body copy"
            name: textBlock
            widget: object
            fields:
              - {
                  label: "Heading",
                  name: heading,
                  widget: string,
                  required: false,
                }
              - { label: "Content", name: content, widget: markdown }
      - {
          label: "Related content",
          name: url,
          title: title,
          hint: "Link to other pages that relate to this content.",
          widget: relation,
          required: false,
          multiple: true,
          collection: pages,
          valueField: "{{slug}}",
          searchFields: ["title"],
          displayFields: ["title"],
        }

      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0, hint: "Where you want this link to appear in the nav",}
      - {
          label: "Meta description",
          name: "meta_description",
          widget: "text",
          required: true
        }
      - {
          label: "Meta keywords",
          name: "meta_keywords",
          widget: list,
          add_to_top: true,
          minimize_collapsed: true,
          required: true,
          summary: '{{fields.name}}',
          field: {label: "Enter a keyword", name: name, widget: string}
        }
      - label: "Exclude from navigation"
        name: eleventyExcludeFromCollections
        required: false
        widget: "boolean"
        default: false
      - label: "Hide from Sitemap"
        name: hide_from_sitemap
        required: false
        widget: "boolean"
        default: false
      - label: "Hide from search engines"
        name: hide_from_robots
        required: false
        widget: "boolean"
        default: false
    meta:
      {
        path:
          {
            widget: string,
            label: "Path",
            index_file: "index",
            hint: "Path can be a sub-folder (e.g. main/sub)",
          },
      }
